name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/marbsangr/action-test:latest .
      env:
        DOCKER_BUILDKIT: 1

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push to GitHub Container Registry
      run: |
        docker push ghcr.io/marbsangr/action-test:latest

  TrendMicroArtifactScan:
    runs-on: ubuntu-latest
    environment: DockerRegistry
    needs: [build]
    steps:
    - name: Vision One Container Security Scan Action
      uses: trendmicro/tmas-scan-action@1.0.10
      with:
          TMAS_API_KEY: ${{ secrets.TMAS_API_KEY }}
          REGION: us-east-1
          SBOM: true
          IMAGE: ghcr.io/marbsangr/action-test:latest
          MAX_TOTAL: 1000
          MAX_CRITICAL: 500
          MAX_HIGH: 500
          MAX_MEDIUM: 500
          MAX_LOW: 500
          MAX_NEGLIGIBLE: 500
          MAX_UNKNOWN: 500
          SCAN_RESULT_ARTIFACT: result.json

    - name: Upload Scan Result Artifact
      uses: actions/upload-artifact@v3
      with:
          name: scan-result
          path: result.json
          retention-days: 30

    - name: Upload SBOM Artifact
      uses: actions/upload-artifact@v3
      with:
          name: sbom
          path: SBOM.json
          retention-days: 30
