name: Trend Vision Artifact Scanner
on: 
  push:
    branches: 
      - master
permissions:
  id-token: write
  contents: read

env:
  IMAGE_NAME: ${{ github.repository }}/actions-test:latest
  

jobs:
    BuildPushImage:
      runs-on: ubuntu-latest
      environment: DockerRegistry
      steps:
        - name: Git clone the repository
          uses: actions/checkout@v4
        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: |
              name/app
              ghcr.io/marbsangr/actions-test:lastest    
            # generate Docker tags based on the following events/attributes
            tags: |
              type=schedule
              type=ref,event=branch
              type=ref,event=pr
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}
              type=semver,pattern={{major}}
              type=sha
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
