- name: Vision One Container Security Scan Action
  uses: trendmicro/tmas-scan-action@version*
   with:
      # Mandatory
      TMAS_API_KEY: ${{ secrets.eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJjaWQiOiJmNzBjNTdmMy0zMjA1LTRiZjAtOTdhZS04MjkwYmU2NGZhNWQiLCJjcGlkIjoic3ZwIiwicHBpZCI6ImN1cyIsIml0IjoxNzA0OTk4OTA0LCJldCI6MTczNjUzNDkwNCwiaWQiOiJjMGVjZjU0NS02NjY1LTRjNWQtOTQxZS02ODE1MjczNDc1YzYiLCJ0b2tlblVzZSI6ImN1c3RvbWVyIn0.tML9qeDYS03jHsOcY-PcjW7072Hbn1EYMzOH-GXoqYciEdmfMXWiUAdNbeEUrXJMOyZ0xcypGa8HYGYDJVuELLcVD4Pa9p8kOYUD6E_tjIPh1Pzd-6ntaPc_Zp4tbXs5dS2B-VV530C2Zbjxh4XEb2c2Wlz2ExyomNnrSznWzw0JxzNa_5XDRSSJkja56AeJ9OXSxO_oXBH6kirgdsgSyldjmuE-eDPL04cF0C9EbVUxHRA5CX3qr3329Y4y2h0MDOvnzvYPMDZkbsX0w_-kCcNAsPz8Rnwu-PZlSnf17gxC2UaTRarq4neaX4AnxQ0UvVFHsZl-flm2lGyBEjPkKANgfloHfwAaJSR3MCAHuojapMB3rIj1pxMWaQJSA7K1tPnPESTNq7ksMKQ9sx37UZytrbDTHtRZF4TJERlbaSvnEAlfViEvKJ8kI7zu1HiQIaIv53W6tVtQsfCFU4rn3KxyK-uVtNWalWt1v8aETiip8M-ell4sDaAZYjYaCU__uXBIpPyWUw3MkB_XfrRXwk_0lxT1_cWZmPv0GiWVhp5Z8Qp2oFjDhQew10wLNMZN28bPnmEJSOKhcsYQqHynTvkXKOmEcvHh1DkbANrtllvC7kfAAkswXbB0Nobp45Ox4JbsEJRVEXES6H4bu1Qf5sxVPnknROQPojrgaBunthM }}
      REGION: us-east-1

      # Optional
      SBOM: true # Saves SBOM to SBOM.json so you can export it as an artifact later.
      MALWARE_SCAN: true # Enable malware scan.
      IMAGE: alpine # The image need to be public or the pipeline need to have access to the private image of choice.
      LOCAL_IMAGE_TARBALL: image.tar
      # For each threshold below, select the maximum number of vulnerabilities that are acceptable.
      MAX_TOTAL: 0
      MAX_CRITICAL: 0
      MAX_HIGH: 0
      MAX_MEDIUM: 0
      MAX_LOW: 0
      MAX_NEGLIGIBLE: 0
      MAX_UNKNOWN: 0
      SCAN_RESULT_ARTIFACT: result.json # Save as an artifact in GitHub to be able to keep the result of the scan.
